import pandas as pd
import json
df = pd.read_csv("reports/security_proximity_alerts_2023_final.csv")
data_json = df.fillna("").to_json(orient="records")
total = len(df)
acres = int(pd.to_numeric(df["Acres"], errors="coerce").fillna(0).sum())
vc = df["Nearest_Base"].astype(str).str.strip().value_counts()
top_base = str(vc.index)
top_count = int(vc.iloc)
china = int(df["China_Flag"].notna().sum())
iran = int(df["Iran_Flag"].notna().sum())
russia = int(df["Russia_Flag"].notna().sum())
markers = ""
for idx, row in df.iterrows():
    code = str(row["Country_Code"])
    if "999" in code: color = "orange"
    elif "998" in code: color = "gray"
    elif "156" in code: color = "red"
    elif "364" in code: color = "purple"
    elif "643" in code: color = "darkred"
    else: color = "blue"
    owner = str(row["Owner"]).replace(chr(39),"").replace(chr(34),"")
    popup = "<b>" + owner + "</b><br>"
    popup += "State: " + str(row["State"]) + "<br>"
    popup += "County: " + str(row["County"]) + "<br>"
    popup += "Country Code: " + str(row["Country_Code"]) + "<br>"
    popup += "Acres: " + str(row["Acres"]) + "<br>"
    popup += "Acquired: " + str(row["Acq_Year"]) + "<br>"
    popup += "Nearest Base: " + str(row["Nearest_Base"]) + "<br>"
    popup += "Distance: " + str(row["Miles_Away"]) + " miles<br>"
    popup += "China: " + str(row["China_Flag"]) + "<br>"
    popup += "Iran: " + str(row["Iran_Flag"]) + "<br>"
    popup += "Russia: " + str(row["Russia_Flag"]) + "<br>"
    popup += "NK: " + str(row["NK_Flag"]) + "<br>"
    lat = str(row[chr(76)+chr(97)+chr(116)])
    lng = str(row[chr(76)+chr(110)+chr(103)])
    m = chr(34)
    markers += chr(76)+chr(46)+chr(99)+chr(105)+chr(114)+chr(99)+chr(108)+chr(101)+chr(77)+chr(97)+chr(114)+chr(107)+chr(101)+chr(114)+chr(40)+chr(91)+lat+chr(44)+lng+chr(93)+chr(44)+chr(123)+chr(114)+chr(97)+chr(100)+chr(105)+chr(117)+chr(115)+chr(58)+chr(56)+chr(44)+chr(99)+chr(111)+chr(108)+chr(111)+chr(114)+chr(58)+m+color+m+chr(44)+chr(102)+chr(105)+chr(108)+chr(108)+chr(67)+chr(111)+chr(108)+chr(111)+chr(114)+chr(58)+m+color+m+chr(44)+chr(102)+chr(105)+chr(108)+chr(108)+chr(79)+chr(112)+chr(97)+chr(99)+chr(105)+chr(116)+chr(121)+chr(58)+chr(48)+chr(46)+chr(55)+chr(125)+chr(41)+chr(46)+chr(98)+chr(105)+chr(110)+chr(100)+chr(80)+chr(111)+chr(112)+chr(117)+chr(112)+chr(40)+m+popup+m+chr(41)+chr(46)+chr(97)+chr(100)+chr(100)+chr(84)+chr(111)+chr(40)+chr(109)+chr(97)+chr(112)+chr(41)+chr(59)+chr(10)
html = []
html.append("<!DOCTYPE html><html><head><title>CFIUS AFIDA Dashboard</title>")
html.append("<link rel=stylesheet href=https://unpkg.com/leaflet@1.9.4/dist/leaflet.css/>")
html.append("<script src=https://unpkg.com/leaflet@1.9.4/dist/leaflet.js></script>")
html.append("<style>")
html.append("body{margin:0;padding:0;}")
html.append("#map{position:absolute;top:0;bottom:0;width:100%;}")
html.append(".panel{position:fixed;background:white;border:3px solid #333;z-index:9999;padding:12px;border-radius:8px;font-family:Arial;font-size:12px;box-shadow:4px 4px 10px rgba(0,0,0,0.4);}")
html.append("#title{top:10px;left:30%;width:420px;text-align:center;}")
html.append("#stats{top:80px;right:20px;width:240px;}")
html.append("#filters{top:80px;left:20px;width:220px;}")
html.append("button{padding:6px;border:none;border-radius:3px;color:white;width:100%;margin-top:5px;cursor:pointer;}")
html.append("</style></head><body>")
html.append("<div id=map></div>")
html.append("<div class=panel id=title>")
html.append("<b style=font-size:15px>AFIDA-Watch: CFIUS Intelligence Dashboard</b><br>")
html.append("<small style=color:green>Real-Time Foreign Holdings Near U.S. Military Bases | DoD CFIUS Support | GAO-24-106337</small>")
html.append("</div>")
html.append("<div class=panel id=stats>")
html.append("<b style=font-size:13px>CFIUS Summary</b><hr>")
html.append("<b>Total Holdings:</b> " + str(total) + "<br>")
html.append("<b>Total Acres:</b> " + str(acres) + "<br>")
html.append("<b>Most Exposed Base:</b><br>" + top_base + "<br>")
html.append("<b>Holdings at Base:</b> " + str(top_count) + "<br><hr>")
html.append("<b style=color:red>China Flagged:</b> " + str(china) + "<br>")
html.append("<b style=color:purple>Iran Flagged:</b> " + str(iran) + "<br>")
html.append("<b style=color:darkred>Russia Flagged:</b> " + str(russia) + "<br><hr>")
html.append("<small>Source: USDA FSA AFIDA 2022-2023<br>GAO-24-106337</small><br>")
html.append("<button style=background:#4CAF50 onclick=downloadCSV()>Download All CSV</button>")
html.append("</div>")
html.append("<div class=panel id=filters>")
html.append("<b style=font-size:13px>CFIUS Summary</b><hr>")
html.append("State: <input type=text id=sf placeholder=OK style=width:65px><br><br>")
html.append("Base: <input type=text id=bf placeholder=Tinker style=width:110px><br><br>")
html.append("Miles: <input type=number id=mf placeholder=50 style=width:50px><br><br>")
html.append("<button style=background:#2196F3 onclick=applyFilter()>Apply Filter</button>")
html.append("<button style=background:#f44336 onclick=resetFilter()>Reset</button>")
html.append("<button style=background:#FF9800 onclick=downloadFiltered()>Download Filtered CSV</button>")
html.append("</div>")
html.append("<script>")
html.append("var map=L.map("map").setView([39.8283,-98.5795],5);")
html.append("L.tileLayer("https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png",{attribution:"CartoDB"}).addTo(map);")
html.append("var allData=" + data_json + ";")
html.append(markers)
html.append("function downloadCSV(){")
html.append("var h=["Owner","State","County","Country_Code","Acres","Acq_Year","Nearest_Base","Miles_Away","China_Flag","Iran_Flag","Russia_Flag","NK_Flag"];")
html.append("var csv=h.join(",")+"\n";")
html.append("allData.forEach(function(r){csv+=[r.Owner,r.State,r.County,r.Country_Code,r.Acres,r.Acq_Year,r.Nearest_Base,r.Miles_Away,r.China_Flag,r.Iran_Flag,r.Russia_Flag,r.NK_Flag].join(",")+"\n";});")
html.append("var b=new Blob([csv],{type:"text/csv"});")
html.append("var a=document.createElement("a");")
html.append("a.href=URL.createObjectURL(b);")
html.append("a.download="CFIUS_Holdings.csv";")
html.append("a.click();}")
html.append("function applyFilter(){")
html.append("var sf=document.getElementById("sf").value.toUpperCase();")
html.append("var bf=document.getElementById("bf").value.toUpperCase();")
html.append("var mf=parseFloat(document.getElementById("mf").value)||999;")
html.append("var filtered=allData.filter(function(r){")
html.append("var sm=!sf||String(r.State).toUpperCase().includes(sf);")
html.append("var bm=!bf||String(r.Nearest_Base).toUpperCase().includes(bf);")
html.append("var mm=!mf||parseFloat(r.Miles_Away)<=mf;")
html.append("return sm&&bm&&mm;});")
html.append("alert("Filtered: "+filtered.length+" holdings found");}")
html.append("function resetFilter(){")
html.append("document.getElementById("sf").value="";")
html.append("document.getElementById("bf").value="";")
html.append("document.getElementById("mf").value="";")
html.append("alert("Filters reset!");}")
html.append("function downloadFiltered(){")
html.append("var sf=document.getElementById("sf").value.toUpperCase();")
html.append("var bf=document.getElementById("bf").value.toUpperCase();")
html.append("var mf=parseFloat(document.getElementById("mf").value)||999;")
html.append("var filtered=allData.filter(function(r){")
html.append("var sm=!sf||String(r.State).toUpperCase().includes(sf);")
html.append("var bm=!bf||String(r.Nearest_Base).toUpperCase().includes(bf);")
html.append("var mm=!mf||parseFloat(r.Miles_Away)<=mf;")
html.append("return sm&&bm&&mm;});")
html.append("var h=["Owner","State","County","Country_Code","Acres","Acq_Year","Nearest_Base","Miles_Away","China_Flag","Iran_Flag","Russia_Flag","NK_Flag"];")
html.append("var csv=h.join(",")+"\n";")
html.append("filtered.forEach(function(r){csv+=[r.Owner,r.State,r.County,r.Country_Code,r.Acres,r.Acq_Year,r.Nearest_Base,r.Miles_Away,r.China_Flag,r.Iran_Flag,r.Russia_Flag,r.NK_Flag].join(",")+"\n";});")
html.append("var b=new Blob([csv],{type:"text/csv"});")
html.append("var a=document.createElement("a");")
html.append("a.href=URL.createObjectURL(b);")
html.append("a.download="CFIUS_Filtered.csv";")
html.append("a.click();}")
html.append("</script></body></html>")
open("reports/CFIUS_DASHBOARD_V4.html","w").write("".join(html))
print("CFIUS Dashboard V4 complete!")
print("Access: http://76.13.58.40:8080/CFIUS_DASHBOARD_V4.html")
